# action.yml
name: 'Instana GitOps: Trigger host agent configuration updates'
description: 'Trigger the GitOps configuration management update by all host agents matching a given zone and or host tags.'
branding:
  icon: repeat
  color: blue
inputs:
  agent_tags:
    description: 'The comma-separated host agent tags to match. Either this input or agent_zone must be set.'
    required: false
  agent_zone:
    description: 'The host agent zone to match. Either this input or agent_tags must be set.'
    required: false
# outputs:
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.agent_tags }}
    - ${{ inputs.agent_zone }}
